// Code generated by ogen, DO NOT EDIT.

package client

// ActivateContentTypeParams is parameters of activateContentType operation.
type ActivateContentTypeParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// CreateDeliveryApiKeyParams is parameters of createDeliveryApiKey operation.
type CreateDeliveryApiKeyParams struct {
	SpaceID string
}

// DeactivateContentTypeParams is parameters of deactivateContentType operation.
type DeactivateContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// DeleteAppInstallationParams is parameters of deleteAppInstallation operation.
type DeleteAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// DeleteContentTypeParams is parameters of deleteContentType operation.
type DeleteContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// DeleteDeliveryApiKeyParams is parameters of deleteDeliveryApiKey operation.
type DeleteDeliveryApiKeyParams struct {
	SpaceID  string
	APIKeyID string
}

// GetAppInstallationParams is parameters of getAppInstallation operation.
type GetAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// GetContentTypeParams is parameters of getContentType operation.
type GetContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// GetDeliveryApiKeyParams is parameters of getDeliveryApiKey operation.
type GetDeliveryApiKeyParams struct {
	SpaceID  string
	APIKeyID string
}

// GetEditorInterfaceParams is parameters of getEditorInterface operation.
type GetEditorInterfaceParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// GetPersonalAccessTokenParams is parameters of getPersonalAccessToken operation.
type GetPersonalAccessTokenParams struct {
	AccessTokenID string
}

// GetPreviewApiKeyParams is parameters of getPreviewApiKey operation.
type GetPreviewApiKeyParams struct {
	SpaceID         string
	PreviewAPIKeyID string
}

// PutAppInstallationParams is parameters of putAppInstallation operation.
type PutAppInstallationParams struct {
	SpaceID                string
	EnvironmentID          string
	AppDefinitionID        string
	XContentfulMarketplace OptString
}

// PutContentTypeParams is parameters of putContentType operation.
type PutContentTypeParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// PutEditorInterfaceParams is parameters of putEditorInterface operation.
type PutEditorInterfaceParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// RevokePersonalAccessTokenParams is parameters of revokePersonalAccessToken operation.
type RevokePersonalAccessTokenParams struct {
	AccessTokenID string
}

// UpdateDeliveryApiKeyParams is parameters of updateDeliveryApiKey operation.
type UpdateDeliveryApiKeyParams struct {
	SpaceID            string
	APIKeyID           string
	XContentfulVersion int
}
