// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AccessToken provides accessToken security value.
	AccessToken(ctx context.Context, operationName string, client *Client) (AccessToken, error)
}

func (s *Client) securityAccessToken(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.AccessToken(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"AccessToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
