// Code generated by ogen, DO NOT EDIT.

package contentfulmanagement

import (
	"bytes"
	"net/http"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodeCreateAppDefinitionRequest(
	req *AppDefinitionData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateDeliveryAPIKeyRequest(
	req *ApiKeyRequestData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateEntryRequest(
	req *EntryRequest,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateOrUpdateEnvironmentRequest(
	req *EnvironmentData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateOrUpdateEnvironmentAliasRequest(
	req *EnvironmentAliasData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreatePersonalAccessTokenRequest(
	req *PersonalAccessTokenRequestData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateRoleRequest(
	req *RoleData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateTeamRequest(
	req *TeamData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateWebhookDefinitionRequest(
	req *WebhookDefinitionData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutAppDefinitionRequest(
	req *AppDefinitionData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutAppInstallationRequest(
	req *AppInstallationData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutAppSigningSecretRequest(
	req *AppSigningSecretRequestData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutContentTypeRequest(
	req *ContentTypeRequestData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutEditorInterfaceRequest(
	req *EditorInterfaceData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutEntryRequest(
	req *EntryRequest,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutExtensionRequest(
	req *ExtensionData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutResourceProviderRequest(
	req *ResourceProviderRequest,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutResourceTypeRequest(
	req *ResourceTypeData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutSpaceEnablementsRequest(
	req *SpaceEnablementData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePutTeamRequest(
	req *TeamData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeUpdateDeliveryAPIKeyRequest(
	req *ApiKeyRequestData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeUpdateRoleRequest(
	req *RoleData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeUpdateWebhookDefinitionRequest(
	req *WebhookDefinitionData,
	r *http.Request,
) error {
	const contentType = "application/vnd.contentful.management.v1+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}
