// Code generated by ogen, DO NOT EDIT.
package client

type DeleteAppInstallationRes interface {
	deleteAppInstallationRes()
}

type GetAppInstallationRes interface {
	getAppInstallationRes()
}

type GetAuthenticatedUserRes interface {
	getAuthenticatedUserRes()
}

type GetEditorInterfaceRes interface {
	getEditorInterfaceRes()
}

type PutAppInstallationRes interface {
	putAppInstallationRes()
}

type PutEditorInterfaceRes interface {
	putEditorInterfaceRes()
}
