// Code generated by ogen, DO NOT EDIT.
package client

type ActivateContentTypeRes interface {
	activateContentTypeRes()
}

type CreateDeliveryApiKeyRes interface {
	createDeliveryApiKeyRes()
}

type CreatePersonalAccessTokenRes interface {
	createPersonalAccessTokenRes()
}

type CreateRoleRes interface {
	createRoleRes()
}

type CreateWebhookDefinitionRes interface {
	createWebhookDefinitionRes()
}

type DeactivateContentTypeRes interface {
	deactivateContentTypeRes()
}

type DeleteAppDefinitionResourceProviderRes interface {
	deleteAppDefinitionResourceProviderRes()
}

type DeleteAppInstallationRes interface {
	deleteAppInstallationRes()
}

type DeleteContentTypeRes interface {
	deleteContentTypeRes()
}

type DeleteDeliveryApiKeyRes interface {
	deleteDeliveryApiKeyRes()
}

type DeleteRoleRes interface {
	deleteRoleRes()
}

type DeleteWebhookDefinitionRes interface {
	deleteWebhookDefinitionRes()
}

type GetAppDefinitionResourceProviderRes interface {
	getAppDefinitionResourceProviderRes()
}

type GetAppInstallationRes interface {
	getAppInstallationRes()
}

type GetAuthenticatedUserRes interface {
	getAuthenticatedUserRes()
}

type GetContentTypeRes interface {
	getContentTypeRes()
}

type GetDeliveryApiKeyRes interface {
	getDeliveryApiKeyRes()
}

type GetEditorInterfaceRes interface {
	getEditorInterfaceRes()
}

type GetPersonalAccessTokenRes interface {
	getPersonalAccessTokenRes()
}

type GetPreviewApiKeyRes interface {
	getPreviewApiKeyRes()
}

type GetRoleRes interface {
	getRoleRes()
}

type GetSpaceEnablementsRes interface {
	getSpaceEnablementsRes()
}

type GetWebhookDefinitionRes interface {
	getWebhookDefinitionRes()
}

type PutAppDefinitionResourceProviderRes interface {
	putAppDefinitionResourceProviderRes()
}

type PutAppInstallationRes interface {
	putAppInstallationRes()
}

type PutContentTypeRes interface {
	putContentTypeRes()
}

type PutEditorInterfaceRes interface {
	putEditorInterfaceRes()
}

type PutSpaceEnablementsRes interface {
	putSpaceEnablementsRes()
}

type RevokePersonalAccessTokenRes interface {
	revokePersonalAccessTokenRes()
}

type UpdateDeliveryApiKeyRes interface {
	updateDeliveryApiKeyRes()
}

type UpdateRoleRes interface {
	updateRoleRes()
}

type UpdateWebhookDefinitionRes interface {
	updateWebhookDefinitionRes()
}
