// Code generated by ogen, DO NOT EDIT.

package client

// DeleteAppInstallationParams is parameters of deleteAppInstallation operation.
type DeleteAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// GetAppInstallationParams is parameters of getAppInstallation operation.
type GetAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// GetEditorInterfaceParams is parameters of getEditorInterface operation.
type GetEditorInterfaceParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// PutAppInstallationParams is parameters of putAppInstallation operation.
type PutAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// PutEditorInterfaceParams is parameters of putEditorInterface operation.
type PutEditorInterfaceParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}
