// Code generated by ogen, DO NOT EDIT.

package contentfulmanagement

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActivateContentType implements activateContentType operation.
	//
	// Activate a content type.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published
	ActivateContentType(ctx context.Context, params ActivateContentTypeParams) (ActivateContentTypeRes, error)
	// CreateAppDefinition implements createAppDefinition operation.
	//
	// Create an app definition.
	//
	// POST /organizations/{organization_id}/app_definitions
	CreateAppDefinition(ctx context.Context, req *AppDefinitionData, params CreateAppDefinitionParams) (CreateAppDefinitionRes, error)
	// CreateDeliveryAPIKey implements createDeliveryAPIKey operation.
	//
	// Create a delivery api key.
	//
	// POST /spaces/{space_id}/api_keys
	CreateDeliveryAPIKey(ctx context.Context, req *ApiKeyRequestData, params CreateDeliveryAPIKeyParams) (CreateDeliveryAPIKeyRes, error)
	// CreateEntry implements createEntry operation.
	//
	// Create an entry.
	//
	// POST /spaces/{space_id}/environments/{environment_id}/entries
	CreateEntry(ctx context.Context, req *EntryRequest, params CreateEntryParams) (CreateEntryRes, error)
	// CreateOrUpdateEnvironment implements createOrUpdateEnvironment operation.
	//
	// Create or update an environment.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}
	CreateOrUpdateEnvironment(ctx context.Context, req *EnvironmentData, params CreateOrUpdateEnvironmentParams) (CreateOrUpdateEnvironmentRes, error)
	// CreateOrUpdateEnvironmentAlias implements createOrUpdateEnvironmentAlias operation.
	//
	// Create/Update an environment alias.
	//
	// PUT /spaces/{space_id}/environment_aliases/{environment_alias_id}
	CreateOrUpdateEnvironmentAlias(ctx context.Context, req *EnvironmentAliasData, params CreateOrUpdateEnvironmentAliasParams) (CreateOrUpdateEnvironmentAliasRes, error)
	// CreatePersonalAccessToken implements createPersonalAccessToken operation.
	//
	// Create a personal access token.
	//
	// POST /users/me/access_tokens
	CreatePersonalAccessToken(ctx context.Context, req *PersonalAccessTokenRequestData) (CreatePersonalAccessTokenRes, error)
	// CreateRole implements createRole operation.
	//
	// Create a role.
	//
	// POST /spaces/{space_id}/roles
	CreateRole(ctx context.Context, req *RoleData, params CreateRoleParams) (CreateRoleRes, error)
	// CreateTeam implements createTeam operation.
	//
	// Create a team.
	//
	// POST /organizations/{organization_id}/teams
	CreateTeam(ctx context.Context, req *TeamData, params CreateTeamParams) (CreateTeamRes, error)
	// CreateTeamSpaceMembership implements createTeamSpaceMembership operation.
	//
	// Create a team space membership.
	//
	// POST /spaces/{space_id}/team_space_memberships
	CreateTeamSpaceMembership(ctx context.Context, req *TeamSpaceMembershipData, params CreateTeamSpaceMembershipParams) (CreateTeamSpaceMembershipRes, error)
	// CreateWebhookDefinition implements createWebhookDefinition operation.
	//
	// Create a webhook definition.
	//
	// POST /spaces/{space_id}/webhook_definitions
	CreateWebhookDefinition(ctx context.Context, req *WebhookDefinitionData, params CreateWebhookDefinitionParams) (CreateWebhookDefinitionRes, error)
	// DeactivateContentType implements deactivateContentType operation.
	//
	// Deactivate a content type.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published
	DeactivateContentType(ctx context.Context, params DeactivateContentTypeParams) (DeactivateContentTypeRes, error)
	// DeleteAppDefinition implements deleteAppDefinition operation.
	//
	// Delete an app definition.
	//
	// DELETE /organizations/{organization_id}/app_definitions/{app_definition_id}
	DeleteAppDefinition(ctx context.Context, params DeleteAppDefinitionParams) (DeleteAppDefinitionRes, error)
	// DeleteAppInstallation implements deleteAppInstallation operation.
	//
	// Uninstall an app.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}
	DeleteAppInstallation(ctx context.Context, params DeleteAppInstallationParams) (DeleteAppInstallationRes, error)
	// DeleteAppSigningSecret implements deleteAppSigningSecret operation.
	//
	// Delete an app signing secret.
	//
	// DELETE /organizations/{organization_id}/app_definitions/{app_definition_id}/signing_secret
	DeleteAppSigningSecret(ctx context.Context, params DeleteAppSigningSecretParams) (DeleteAppSigningSecretRes, error)
	// DeleteContentType implements deleteContentType operation.
	//
	// Delete a content type.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}
	DeleteContentType(ctx context.Context, params DeleteContentTypeParams) (DeleteContentTypeRes, error)
	// DeleteDeliveryAPIKey implements deleteDeliveryAPIKey operation.
	//
	// Delete a single delivery api key.
	//
	// DELETE /spaces/{space_id}/api_keys/{api_key_id}
	DeleteDeliveryAPIKey(ctx context.Context, params DeleteDeliveryAPIKeyParams) (DeleteDeliveryAPIKeyRes, error)
	// DeleteEntry implements deleteEntry operation.
	//
	// Delete an entry.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/entries/{entry_id}
	DeleteEntry(ctx context.Context, params DeleteEntryParams) (DeleteEntryRes, error)
	// DeleteEnvironment implements deleteEnvironment operation.
	//
	// Delete an environment.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}
	DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (DeleteEnvironmentRes, error)
	// DeleteEnvironmentAlias implements deleteEnvironmentAlias operation.
	//
	// Delete an environment alias.
	//
	// DELETE /spaces/{space_id}/environment_aliases/{environment_alias_id}
	DeleteEnvironmentAlias(ctx context.Context, params DeleteEnvironmentAliasParams) (DeleteEnvironmentAliasRes, error)
	// DeleteExtension implements deleteExtension operation.
	//
	// Delete an extension.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}
	DeleteExtension(ctx context.Context, params DeleteExtensionParams) (DeleteExtensionRes, error)
	// DeleteResourceProvider implements deleteResourceProvider operation.
	//
	// Delete a resource provider definition.
	//
	// DELETE /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider
	DeleteResourceProvider(ctx context.Context, params DeleteResourceProviderParams) (DeleteResourceProviderRes, error)
	// DeleteResourceType implements deleteResourceType operation.
	//
	// Delete a resource type definition.
	//
	// DELETE /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider/resource_types/{resource_type_id}
	DeleteResourceType(ctx context.Context, params DeleteResourceTypeParams) (DeleteResourceTypeRes, error)
	// DeleteRole implements deleteRole operation.
	//
	// Delete a role.
	//
	// DELETE /spaces/{space_id}/roles/{role_id}
	DeleteRole(ctx context.Context, params DeleteRoleParams) (DeleteRoleRes, error)
	// DeleteTag implements deleteTag operation.
	//
	// Delete a tag.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/tags/{tag_id}
	DeleteTag(ctx context.Context, params DeleteTagParams) (DeleteTagRes, error)
	// DeleteTeam implements deleteTeam operation.
	//
	// Delete a team.
	//
	// DELETE /organizations/{organization_id}/teams/{team_id}
	DeleteTeam(ctx context.Context, params DeleteTeamParams) (DeleteTeamRes, error)
	// DeleteTeamSpaceMembership implements deleteTeamSpaceMembership operation.
	//
	// Delete a team space membership.
	//
	// DELETE /spaces/{space_id}/team_space_memberships/{team_space_membership_id}
	DeleteTeamSpaceMembership(ctx context.Context, params DeleteTeamSpaceMembershipParams) (DeleteTeamSpaceMembershipRes, error)
	// DeleteWebhookDefinition implements deleteWebhookDefinition operation.
	//
	// Delete a webhook definition.
	//
	// DELETE /spaces/{space_id}/webhook_definitions/{webhook_definition_id}
	DeleteWebhookDefinition(ctx context.Context, params DeleteWebhookDefinitionParams) (DeleteWebhookDefinitionRes, error)
	// GetAppDefinition implements getAppDefinition operation.
	//
	// Get one app definition.
	//
	// GET /organizations/{organization_id}/app_definitions/{app_definition_id}
	GetAppDefinition(ctx context.Context, params GetAppDefinitionParams) (GetAppDefinitionRes, error)
	// GetAppInstallation implements getAppInstallation operation.
	//
	// Get one app installation.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}
	GetAppInstallation(ctx context.Context, params GetAppInstallationParams) (GetAppInstallationRes, error)
	// GetAppSigningSecret implements getAppSigningSecret operation.
	//
	// Get one app signing secret.
	//
	// GET /organizations/{organization_id}/app_definitions/{app_definition_id}/signing_secret
	GetAppSigningSecret(ctx context.Context, params GetAppSigningSecretParams) (GetAppSigningSecretRes, error)
	// GetAuthenticatedUser implements getAuthenticatedUser operation.
	//
	// Get the authenticated user.
	//
	// GET /users/me
	GetAuthenticatedUser(ctx context.Context) (GetAuthenticatedUserRes, error)
	// GetContentType implements getContentType operation.
	//
	// Get a content type.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}
	GetContentType(ctx context.Context, params GetContentTypeParams) (GetContentTypeRes, error)
	// GetContentTypes implements getContentTypes operation.
	//
	// Get a collection of content types.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/content_types
	GetContentTypes(ctx context.Context, params GetContentTypesParams) (GetContentTypesRes, error)
	// GetDeliveryAPIKey implements getDeliveryAPIKey operation.
	//
	// Get a single delivery api key.
	//
	// GET /spaces/{space_id}/api_keys/{api_key_id}
	GetDeliveryAPIKey(ctx context.Context, params GetDeliveryAPIKeyParams) (GetDeliveryAPIKeyRes, error)
	// GetEditorInterface implements getEditorInterface operation.
	//
	// Get the editor interface for a content type.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface
	GetEditorInterface(ctx context.Context, params GetEditorInterfaceParams) (GetEditorInterfaceRes, error)
	// GetEntries implements getEntries operation.
	//
	// Get all entries of a space.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/entries
	GetEntries(ctx context.Context, params GetEntriesParams) (GetEntriesRes, error)
	// GetEntry implements getEntry operation.
	//
	// Get a single entry.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/entries/{entry_id}
	GetEntry(ctx context.Context, params GetEntryParams) (GetEntryRes, error)
	// GetEnvironment implements getEnvironment operation.
	//
	// Get a single environment.
	//
	// GET /spaces/{space_id}/environments/{environment_id}
	GetEnvironment(ctx context.Context, params GetEnvironmentParams) (GetEnvironmentRes, error)
	// GetEnvironmentAlias implements getEnvironmentAlias operation.
	//
	// Get a single environment alias.
	//
	// GET /spaces/{space_id}/environment_aliases/{environment_alias_id}
	GetEnvironmentAlias(ctx context.Context, params GetEnvironmentAliasParams) (GetEnvironmentAliasRes, error)
	// GetExtension implements getExtension operation.
	//
	// Get a single extension.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}
	GetExtension(ctx context.Context, params GetExtensionParams) (GetExtensionRes, error)
	// GetMarketplaceAppDefinitions implements getMarketplaceAppDefinitions operation.
	//
	// Get marketplace app definitions.
	//
	// GET /app_definitions
	GetMarketplaceAppDefinitions(ctx context.Context, params GetMarketplaceAppDefinitionsParams) (GetMarketplaceAppDefinitionsRes, error)
	// GetPersonalAccessToken implements getPersonalAccessToken operation.
	//
	// Get a single personal access token.
	//
	// GET /users/me/access_tokens/{access_token_id}
	GetPersonalAccessToken(ctx context.Context, params GetPersonalAccessTokenParams) (GetPersonalAccessTokenRes, error)
	// GetPreviewAPIKey implements getPreviewAPIKey operation.
	//
	// Get a single preview api key.
	//
	// GET /spaces/{space_id}/preview_api_keys/{preview_api_key_id}
	GetPreviewAPIKey(ctx context.Context, params GetPreviewAPIKeyParams) (GetPreviewAPIKeyRes, error)
	// GetResourceProvider implements getResourceProvider operation.
	//
	// Get one resource provider definition.
	//
	// GET /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider
	GetResourceProvider(ctx context.Context, params GetResourceProviderParams) (GetResourceProviderRes, error)
	// GetResourceType implements getResourceType operation.
	//
	// Get one resource type definition.
	//
	// GET /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider/resource_types/{resource_type_id}
	GetResourceType(ctx context.Context, params GetResourceTypeParams) (GetResourceTypeRes, error)
	// GetRole implements getRole operation.
	//
	// Get a role.
	//
	// GET /spaces/{space_id}/roles/{role_id}
	GetRole(ctx context.Context, params GetRoleParams) (GetRoleRes, error)
	// GetSpaceEnablements implements getSpaceEnablements operation.
	//
	// Get enablements for a space.
	//
	// GET /spaces/{space_id}/enablements
	GetSpaceEnablements(ctx context.Context, params GetSpaceEnablementsParams) (GetSpaceEnablementsRes, error)
	// GetTag implements getTag operation.
	//
	// Get a single tag.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/tags/{tag_id}
	GetTag(ctx context.Context, params GetTagParams) (GetTagRes, error)
	// GetTags implements getTags operation.
	//
	// Get a collection of tags.
	//
	// GET /spaces/{space_id}/environments/{environment_id}/tags
	GetTags(ctx context.Context, params GetTagsParams) (GetTagsRes, error)
	// GetTeam implements getTeam operation.
	//
	// Get a single team.
	//
	// GET /organizations/{organization_id}/teams/{team_id}
	GetTeam(ctx context.Context, params GetTeamParams) (GetTeamRes, error)
	// GetTeamSpaceMembership implements getTeamSpaceMembership operation.
	//
	// Get a single team space membership.
	//
	// GET /spaces/{space_id}/team_space_memberships/{team_space_membership_id}
	GetTeamSpaceMembership(ctx context.Context, params GetTeamSpaceMembershipParams) (GetTeamSpaceMembershipRes, error)
	// GetWebhookDefinition implements getWebhookDefinition operation.
	//
	// Get a webhook definition.
	//
	// GET /spaces/{space_id}/webhook_definitions/{webhook_definition_id}
	GetWebhookDefinition(ctx context.Context, params GetWebhookDefinitionParams) (GetWebhookDefinitionRes, error)
	// PublishEntry implements publishEntry operation.
	//
	// Publish an entry.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published
	PublishEntry(ctx context.Context, params PublishEntryParams) (PublishEntryRes, error)
	// PutAppDefinition implements putAppDefinition operation.
	//
	// Create or update an app definition.
	//
	// PUT /organizations/{organization_id}/app_definitions/{app_definition_id}
	PutAppDefinition(ctx context.Context, req *AppDefinitionData, params PutAppDefinitionParams) (PutAppDefinitionRes, error)
	// PutAppInstallation implements putAppInstallation operation.
	//
	// Install or update an app.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}
	PutAppInstallation(ctx context.Context, req *AppInstallationData, params PutAppInstallationParams) (PutAppInstallationRes, error)
	// PutAppSigningSecret implements putAppSigningSecret operation.
	//
	// Create or update an app signing secret.
	//
	// PUT /organizations/{organization_id}/app_definitions/{app_definition_id}/signing_secret
	PutAppSigningSecret(ctx context.Context, req *AppSigningSecretRequestData, params PutAppSigningSecretParams) (PutAppSigningSecretRes, error)
	// PutContentType implements putContentType operation.
	//
	// Update a content type.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}
	PutContentType(ctx context.Context, req *ContentTypeRequestData, params PutContentTypeParams) (PutContentTypeRes, error)
	// PutEditorInterface implements putEditorInterface operation.
	//
	// Update the editor interface for a content type.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface
	PutEditorInterface(ctx context.Context, req *EditorInterfaceData, params PutEditorInterfaceParams) (PutEditorInterfaceRes, error)
	// PutEntry implements putEntry operation.
	//
	// Create or update an entry.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/entries/{entry_id}
	PutEntry(ctx context.Context, req *EntryRequest, params PutEntryParams) (PutEntryRes, error)
	// PutExtension implements putExtension operation.
	//
	// Create or update an extension.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}
	PutExtension(ctx context.Context, req *ExtensionData, params PutExtensionParams) (PutExtensionRes, error)
	// PutResourceProvider implements putResourceProvider operation.
	//
	// Create or update a resource provider definition.
	//
	// PUT /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider
	PutResourceProvider(ctx context.Context, req *ResourceProviderRequest, params PutResourceProviderParams) (PutResourceProviderRes, error)
	// PutResourceType implements putResourceType operation.
	//
	// Create or update a resource type definition.
	//
	// PUT /organizations/{organization_id}/app_definitions/{app_definition_id}/resource_provider/resource_types/{resource_type_id}
	PutResourceType(ctx context.Context, req *ResourceTypeData, params PutResourceTypeParams) (PutResourceTypeRes, error)
	// PutSpaceEnablements implements putSpaceEnablements operation.
	//
	// Update enablements for a space.
	//
	// PUT /spaces/{space_id}/enablements
	PutSpaceEnablements(ctx context.Context, req *SpaceEnablementData, params PutSpaceEnablementsParams) (PutSpaceEnablementsRes, error)
	// PutTag implements putTag operation.
	//
	// Create or update a tag.
	//
	// PUT /spaces/{space_id}/environments/{environment_id}/tags/{tag_id}
	PutTag(ctx context.Context, req *TagRequest, params PutTagParams) (PutTagRes, error)
	// PutTeam implements putTeam operation.
	//
	// Update a single team.
	//
	// PUT /organizations/{organization_id}/teams/{team_id}
	PutTeam(ctx context.Context, req *TeamData, params PutTeamParams) (PutTeamRes, error)
	// PutTeamSpaceMembership implements putTeamSpaceMembership operation.
	//
	// Update a single team space membership.
	//
	// PUT /spaces/{space_id}/team_space_memberships/{team_space_membership_id}
	PutTeamSpaceMembership(ctx context.Context, req *TeamSpaceMembershipData, params PutTeamSpaceMembershipParams) (PutTeamSpaceMembershipRes, error)
	// RevokePersonalAccessToken implements revokePersonalAccessToken operation.
	//
	// Revoke a personal access token.
	//
	// PUT /users/me/access_tokens/{access_token_id}/revoked
	RevokePersonalAccessToken(ctx context.Context, params RevokePersonalAccessTokenParams) (RevokePersonalAccessTokenRes, error)
	// UnpublishEntry implements unpublishEntry operation.
	//
	// Unpublish an entry.
	//
	// DELETE /spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published
	UnpublishEntry(ctx context.Context, params UnpublishEntryParams) (UnpublishEntryRes, error)
	// UpdateDeliveryAPIKey implements updateDeliveryAPIKey operation.
	//
	// Update a single delivery api key.
	//
	// PUT /spaces/{space_id}/api_keys/{api_key_id}
	UpdateDeliveryAPIKey(ctx context.Context, req *ApiKeyRequestData, params UpdateDeliveryAPIKeyParams) (UpdateDeliveryAPIKeyRes, error)
	// UpdateRole implements updateRole operation.
	//
	// Update a role.
	//
	// PUT /spaces/{space_id}/roles/{role_id}
	UpdateRole(ctx context.Context, req *RoleData, params UpdateRoleParams) (UpdateRoleRes, error)
	// UpdateWebhookDefinition implements updateWebhookDefinition operation.
	//
	// Update a webhook definition.
	//
	// PUT /spaces/{space_id}/webhook_definitions/{webhook_definition_id}
	UpdateWebhookDefinition(ctx context.Context, req *WebhookDefinitionData, params UpdateWebhookDefinitionParams) (UpdateWebhookDefinitionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
