// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	ActivateContentTypeOperation                 OperationName = "ActivateContentType"
	CreateDeliveryApiKeyOperation                OperationName = "CreateDeliveryApiKey"
	CreatePersonalAccessTokenOperation           OperationName = "CreatePersonalAccessToken"
	CreateRoleOperation                          OperationName = "CreateRole"
	CreateWebhookDefinitionOperation             OperationName = "CreateWebhookDefinition"
	DeactivateContentTypeOperation               OperationName = "DeactivateContentType"
	DeleteAppDefinitionResourceProviderOperation OperationName = "DeleteAppDefinitionResourceProvider"
	DeleteAppInstallationOperation               OperationName = "DeleteAppInstallation"
	DeleteContentTypeOperation                   OperationName = "DeleteContentType"
	DeleteDeliveryApiKeyOperation                OperationName = "DeleteDeliveryApiKey"
	DeleteRoleOperation                          OperationName = "DeleteRole"
	DeleteWebhookDefinitionOperation             OperationName = "DeleteWebhookDefinition"
	GetAppDefinitionResourceProviderOperation    OperationName = "GetAppDefinitionResourceProvider"
	GetAppInstallationOperation                  OperationName = "GetAppInstallation"
	GetAuthenticatedUserOperation                OperationName = "GetAuthenticatedUser"
	GetContentTypeOperation                      OperationName = "GetContentType"
	GetDeliveryApiKeyOperation                   OperationName = "GetDeliveryApiKey"
	GetEditorInterfaceOperation                  OperationName = "GetEditorInterface"
	GetPersonalAccessTokenOperation              OperationName = "GetPersonalAccessToken"
	GetPreviewApiKeyOperation                    OperationName = "GetPreviewApiKey"
	GetRoleOperation                             OperationName = "GetRole"
	GetSpaceEnablementsOperation                 OperationName = "GetSpaceEnablements"
	GetWebhookDefinitionOperation                OperationName = "GetWebhookDefinition"
	PutAppDefinitionResourceProviderOperation    OperationName = "PutAppDefinitionResourceProvider"
	PutAppInstallationOperation                  OperationName = "PutAppInstallation"
	PutContentTypeOperation                      OperationName = "PutContentType"
	PutEditorInterfaceOperation                  OperationName = "PutEditorInterface"
	PutSpaceEnablementsOperation                 OperationName = "PutSpaceEnablements"
	RevokePersonalAccessTokenOperation           OperationName = "RevokePersonalAccessToken"
	UpdateDeliveryApiKeyOperation                OperationName = "UpdateDeliveryApiKey"
	UpdateRoleOperation                          OperationName = "UpdateRole"
	UpdateWebhookDefinitionOperation             OperationName = "UpdateWebhookDefinition"
)
