// Code generated by ogen, DO NOT EDIT.

package contentfulmanagement

// ActivateContentTypeParams is parameters of activateContentType operation.
type ActivateContentTypeParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// CreateAppDefinitionParams is parameters of createAppDefinition operation.
type CreateAppDefinitionParams struct {
	OrganizationID string
}

// CreateDeliveryApiKeyParams is parameters of createDeliveryApiKey operation.
type CreateDeliveryApiKeyParams struct {
	SpaceID string
}

// CreateRoleParams is parameters of createRole operation.
type CreateRoleParams struct {
	SpaceID string
}

// CreateWebhookDefinitionParams is parameters of createWebhookDefinition operation.
type CreateWebhookDefinitionParams struct {
	SpaceID string
}

// DeactivateContentTypeParams is parameters of deactivateContentType operation.
type DeactivateContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// DeleteAppDefinitionParams is parameters of deleteAppDefinition operation.
type DeleteAppDefinitionParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// DeleteAppDefinitionResourceProviderParams is parameters of deleteAppDefinitionResourceProvider operation.
type DeleteAppDefinitionResourceProviderParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// DeleteAppDefinitionResourceTypeParams is parameters of deleteAppDefinitionResourceType operation.
type DeleteAppDefinitionResourceTypeParams struct {
	OrganizationID  string
	AppDefinitionID string
	ResourceTypeID  string
}

// DeleteAppInstallationParams is parameters of deleteAppInstallation operation.
type DeleteAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// DeleteContentTypeParams is parameters of deleteContentType operation.
type DeleteContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// DeleteDeliveryApiKeyParams is parameters of deleteDeliveryApiKey operation.
type DeleteDeliveryApiKeyParams struct {
	SpaceID  string
	APIKeyID string
}

// DeleteExtensionParams is parameters of deleteExtension operation.
type DeleteExtensionParams struct {
	SpaceID       string
	EnvironmentID string
	ExtensionID   string
}

// DeleteRoleParams is parameters of deleteRole operation.
type DeleteRoleParams struct {
	SpaceID string
	RoleID  string
}

// DeleteWebhookDefinitionParams is parameters of deleteWebhookDefinition operation.
type DeleteWebhookDefinitionParams struct {
	SpaceID             string
	WebhookDefinitionID string
}

// GetAppDefinitionParams is parameters of getAppDefinition operation.
type GetAppDefinitionParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// GetAppDefinitionResourceProviderParams is parameters of getAppDefinitionResourceProvider operation.
type GetAppDefinitionResourceProviderParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// GetAppDefinitionResourceTypeParams is parameters of getAppDefinitionResourceType operation.
type GetAppDefinitionResourceTypeParams struct {
	OrganizationID  string
	AppDefinitionID string
	ResourceTypeID  string
}

// GetAppInstallationParams is parameters of getAppInstallation operation.
type GetAppInstallationParams struct {
	SpaceID         string
	EnvironmentID   string
	AppDefinitionID string
}

// GetContentTypeParams is parameters of getContentType operation.
type GetContentTypeParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// GetDeliveryApiKeyParams is parameters of getDeliveryApiKey operation.
type GetDeliveryApiKeyParams struct {
	SpaceID  string
	APIKeyID string
}

// GetEditorInterfaceParams is parameters of getEditorInterface operation.
type GetEditorInterfaceParams struct {
	SpaceID       string
	EnvironmentID string
	ContentTypeID string
}

// GetExtensionParams is parameters of getExtension operation.
type GetExtensionParams struct {
	SpaceID       string
	EnvironmentID string
	ExtensionID   string
}

// GetPersonalAccessTokenParams is parameters of getPersonalAccessToken operation.
type GetPersonalAccessTokenParams struct {
	AccessTokenID string
}

// GetPreviewApiKeyParams is parameters of getPreviewApiKey operation.
type GetPreviewApiKeyParams struct {
	SpaceID         string
	PreviewAPIKeyID string
}

// GetRoleParams is parameters of getRole operation.
type GetRoleParams struct {
	SpaceID string
	RoleID  string
}

// GetSpaceEnablementsParams is parameters of getSpaceEnablements operation.
type GetSpaceEnablementsParams struct {
	SpaceID string
}

// GetWebhookDefinitionParams is parameters of getWebhookDefinition operation.
type GetWebhookDefinitionParams struct {
	SpaceID             string
	WebhookDefinitionID string
}

// PutAppDefinitionParams is parameters of putAppDefinition operation.
type PutAppDefinitionParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// PutAppDefinitionResourceProviderParams is parameters of putAppDefinitionResourceProvider operation.
type PutAppDefinitionResourceProviderParams struct {
	OrganizationID  string
	AppDefinitionID string
}

// PutAppDefinitionResourceTypeParams is parameters of putAppDefinitionResourceType operation.
type PutAppDefinitionResourceTypeParams struct {
	OrganizationID  string
	AppDefinitionID string
	ResourceTypeID  string
}

// PutAppInstallationParams is parameters of putAppInstallation operation.
type PutAppInstallationParams struct {
	SpaceID                string
	EnvironmentID          string
	AppDefinitionID        string
	XContentfulMarketplace OptString
}

// PutContentTypeParams is parameters of putContentType operation.
type PutContentTypeParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// PutEditorInterfaceParams is parameters of putEditorInterface operation.
type PutEditorInterfaceParams struct {
	SpaceID            string
	EnvironmentID      string
	ContentTypeID      string
	XContentfulVersion int
}

// PutExtensionParams is parameters of putExtension operation.
type PutExtensionParams struct {
	SpaceID            string
	EnvironmentID      string
	ExtensionID        string
	XContentfulVersion int
}

// PutSpaceEnablementsParams is parameters of putSpaceEnablements operation.
type PutSpaceEnablementsParams struct {
	SpaceID            string
	XContentfulVersion int
}

// RevokePersonalAccessTokenParams is parameters of revokePersonalAccessToken operation.
type RevokePersonalAccessTokenParams struct {
	AccessTokenID string
}

// UpdateDeliveryApiKeyParams is parameters of updateDeliveryApiKey operation.
type UpdateDeliveryApiKeyParams struct {
	SpaceID            string
	APIKeyID           string
	XContentfulVersion int
}

// UpdateRoleParams is parameters of updateRole operation.
type UpdateRoleParams struct {
	SpaceID            string
	RoleID             string
	XContentfulVersion int
}

// UpdateWebhookDefinitionParams is parameters of updateWebhookDefinition operation.
type UpdateWebhookDefinitionParams struct {
	SpaceID             string
	WebhookDefinitionID string
	XContentfulVersion  int
}
