// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PreviewApiKeyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_token": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"environments": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"preview_api_key_id": schema.StringAttribute{
				Required: true,
			},
			"space_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type PreviewApiKeyModel struct {
	AccessToken     types.String `tfsdk:"access_token"`
	Description     types.String `tfsdk:"description"`
	Environments    types.List   `tfsdk:"environments"`
	Name            types.String `tfsdk:"name"`
	PreviewApiKeyId types.String `tfsdk:"preview_api_key_id"`
	SpaceId         types.String `tfsdk:"space_id"`
}
