package provider_test

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	. "github.com/cysp/terraform-provider-contentful/internal/provider"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	frameworklist "github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProviderSurfaceDocumentation(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	provider := New("test")

	testProviderDocumentation(t, providerDocumentationTest{
		category:        "resources",
		documentKind:    "Resource",
		exampleFilename: "resource.tf",
		registeredTypes: resourceTypeNames(ctx, provider.Resources(ctx)),
	})
	testProviderDocumentation(t, providerDocumentationTest{
		category:        "data-sources",
		documentKind:    "Data Source",
		exampleFilename: "data-source.tf",
		registeredTypes: dataSourceTypeNames(ctx, provider.DataSources(ctx)),
	})
	testProviderDocumentation(t, providerDocumentationTest{
		category:        "list-resources",
		documentKind:    "List Resource",
		exampleFilename: "list-resource.tfquery.hcl",
		registeredTypes: listResourceTypeNames(ctx, provider.ListResources(ctx)),
	})
}

type providerDocumentationTest struct {
	category        string
	documentKind    string
	exampleFilename string
	registeredTypes []string
}

func testProviderDocumentation(t *testing.T, test providerDocumentationTest) {
	t.Helper()
	t.Run(test.category, func(t *testing.T) {
		t.Parallel()

		repositoryRoot := filepath.Join("..", "..")
		documentationDirectory := filepath.Join(repositoryRoot, "docs", test.category)
		exampleDirectory := filepath.Join(repositoryRoot, "examples", test.category)

		require.NotEmpty(t, test.registeredTypes)
		require.Len(t, uniqueStrings(test.registeredTypes), len(test.registeredTypes), "provider type names must be unique")

		registeredTypes := append([]string(nil), test.registeredTypes...)
		sort.Strings(registeredTypes)

		documentedTypes := documentationTypeNames(t, documentationDirectory)
		assert.Equal(t, registeredTypes, documentedTypes, "generated documentation must exactly cover registered provider types")
		assert.Subset(
			t,
			registeredTypes,
			exampleTypeNames(t, exampleDirectory, test.exampleFilename),
			"generator examples must only describe registered provider types",
		)

		for _, typeName := range registeredTypes {
			documentPath := filepath.Join(documentationDirectory, strings.TrimPrefix(typeName, "contentful_")+".md")
			document, readErr := os.ReadFile(documentPath)
			require.NoError(t, readErr)
			assert.Contains(t, string(document), "# "+typeName+" ("+test.documentKind+")")
			assert.Contains(t, string(document), "# generated by https://github.com/hashicorp/terraform-plugin-docs")
		}
	})
}

func exampleTypeNames(t *testing.T, directory string, exampleFilename string) []string {
	t.Helper()

	entries, err := os.ReadDir(directory)
	require.NoError(t, err)

	typeNames := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		_, statErr := os.Stat(filepath.Join(directory, entry.Name(), exampleFilename))
		require.NoError(t, statErr, "%s must contain %s", entry.Name(), exampleFilename)
		typeNames = append(typeNames, entry.Name())
	}

	sort.Strings(typeNames)

	return typeNames
}

func resourceTypeNames(ctx context.Context, factories []func() resource.Resource) []string {
	typeNames := make([]string, 0, len(factories))
	for _, factory := range factories {
		response := resource.MetadataResponse{}
		factory().Metadata(ctx, resource.MetadataRequest{ProviderTypeName: "contentful"}, &response)
		typeNames = append(typeNames, response.TypeName)
	}

	return typeNames
}

func dataSourceTypeNames(ctx context.Context, factories []func() datasource.DataSource) []string {
	typeNames := make([]string, 0, len(factories))
	for _, factory := range factories {
		response := datasource.MetadataResponse{}
		factory().Metadata(ctx, datasource.MetadataRequest{ProviderTypeName: "contentful"}, &response)
		typeNames = append(typeNames, response.TypeName)
	}

	return typeNames
}

func listResourceTypeNames(ctx context.Context, factories []func() frameworklist.ListResource) []string {
	typeNames := make([]string, 0, len(factories))
	for _, factory := range factories {
		response := resource.MetadataResponse{}
		factory().Metadata(ctx, resource.MetadataRequest{ProviderTypeName: "contentful"}, &response)
		typeNames = append(typeNames, response.TypeName)
	}

	return typeNames
}

func documentationTypeNames(t *testing.T, directory string) []string {
	t.Helper()

	entries, err := os.ReadDir(directory)
	require.NoError(t, err)

	typeNames := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}

		typeNames = append(typeNames, "contentful_"+strings.TrimSuffix(entry.Name(), ".md"))
	}

	sort.Strings(typeNames)

	return typeNames
}

func uniqueStrings(values []string) []string {
	unique := make(map[string]struct{}, len(values))
	for _, value := range values {
		unique[value] = struct{}{}
	}

	result := make([]string, 0, len(unique))
	for value := range unique {
		result = append(result, value)
	}

	return result
}
