package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func LocaleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "Manages a Contentful Locale in a space's environment. The locale code identifies localized content; Contentful generates a separate system ID. Destroying a locale permanently deletes its localized content. Contentful rejects deletion of the default locale or a locale used as a fallback.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Composite Terraform resource identifier in `space_id/environment_id/locale_id` form.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"space_id": schema.StringAttribute{
				Description: "ID of the space containing the locale. Changing this value replaces the resource.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"environment_id": schema.StringAttribute{
				Description: "ID of the environment containing the locale. Use a concrete environment ID for a stable management target. Changing this value replaces the resource.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"locale_id": schema.StringAttribute{
				Description: "System ID generated by Contentful, distinct from the locale code.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the locale.",
				Required:    true,
			},
			"code": schema.StringAttribute{
				Description: "Locale code, for example `en-US`. Changing it updates the locale in place and affects subsequent content API responses. Contentful rejects a code change while another locale uses it as a fallback.",
				Required:    true,
			},
			"fallback_code": schema.StringAttribute{
				Description: "Code of an existing locale to use when translated content is missing. Fallback chains cannot contain cycles. Omission sends null to clear the fallback; an empty string is sent unchanged for Contentful to validate.",
				Optional:    true,
			},
			"content_delivery_api": schema.BoolAttribute{
				Description: "Whether localized content is included in Content Delivery API and Content Preview API responses. Defaults to true. Clear dependent fallbacks before disabling delivery.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"content_management_api": schema.BoolAttribute{
				Description: "Whether localized content is available through the Content Management API and for editing in the web app. Disabling it hides localized Entry and Asset fields from management reads and rejects writes containing that code; the Locale entity remains discoverable. Defaults to true.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"optional": schema.BoolAttribute{
				Description: "Whether required localized fields may be empty for this locale when publishing all locales together. This does not relax required fields in the default locale. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"default": schema.BoolAttribute{
				Description: "Whether this is the environment's default locale. Contentful does not allow changing this status.",
				Computed:    true,
			},
			"timeouts": timeouts.AttributesAll(ctx),
		},
	}
}
