package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func LocaleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "Manages a Contentful Locale in an environment. The locale code identifies translated content; Contentful generates a separate system ID. Destroying a locale permanently deletes its associated localized content. Contentful rejects deletion while another locale uses it as a fallback. Import existing locales before managing them. If creation returns an ambiguous error, inspect Contentful and import any created locale before trying again.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Composite Terraform resource identifier in `space_id/environment_id/locale_id` form.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"space_id": schema.StringAttribute{
				Description: "ID of the space containing the locale. Changing this value replaces the resource.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"environment_id": schema.StringAttribute{
				Description: "ID of the environment containing the locale. Use a concrete environment ID for a stable management target. Changing this value replaces the resource.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"locale_id": schema.StringAttribute{
				Description: "System ID generated by Contentful, distinct from the locale code.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the locale.",
				Required:    true,
			},
			"code": schema.StringAttribute{
				Description: "Locale code, for example `en-US`. Changing it updates the locale in place and affects subsequent content API responses. Contentful rejects a code change while another locale uses it as a fallback.",
				Required:    true,
			},
			"fallback_code": schema.StringAttribute{
				Description: "Locale code to use when translated content is missing. Omission sends null to clear the fallback; an empty string is sent unchanged for Contentful to validate.",
				Optional:    true,
			},
			"content_delivery_api": schema.BoolAttribute{
				Description: "Whether the locale is available through the Content Delivery API. Defaults to true.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"content_management_api": schema.BoolAttribute{
				Description: "Whether the locale is available through the Content Management API. Defaults to true.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"optional": schema.BoolAttribute{
				Description: "Whether the locale can be empty for required localized fields. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"default": schema.BoolAttribute{
				Description: "Whether this is the environment's default locale. This property cannot be changed through this resource.",
				Computed:    true,
			},
			"timeouts": timeouts.AttributesAll(ctx),
		},
	}
}
