// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_app_definition

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AppDefinitionDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_definition_id": schema.StringAttribute{
				Required: true,
			},
			"bundle": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: BundleType{
					ObjectType: types.ObjectType{
						AttrTypes: BundleValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
			"src": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type AppDefinitionModel struct {
	AppDefinitionId types.String `tfsdk:"app_definition_id"`
	Bundle          BundleValue  `tfsdk:"bundle"`
	Description     types.String `tfsdk:"description"`
	Name            types.String `tfsdk:"name"`
	OrganizationId  types.String `tfsdk:"organization_id"`
	Src             types.String `tfsdk:"src"`
}

var _ basetypes.ObjectTypable = BundleType{}

type BundleType struct {
	basetypes.ObjectType
}

func (t BundleType) Equal(o attr.Type) bool {
	other, ok := o.(BundleType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BundleType) String() string {
	return "BundleType"
}

func (t BundleType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BundleValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewBundleValueNull() BundleValue {
	return BundleValue{
		state: attr.ValueStateNull,
	}
}

func NewBundleValueUnknown() BundleValue {
	return BundleValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBundleValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BundleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BundleValue Attribute Value",
				"While creating a BundleValue value, a missing attribute value was detected. "+
					"A BundleValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BundleValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BundleValue Attribute Type",
				"While creating a BundleValue value, an invalid attribute value was detected. "+
					"A BundleValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BundleValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BundleValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BundleValue Attribute Value",
				"While creating a BundleValue value, an extra attribute value was detected. "+
					"A BundleValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BundleValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBundleValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewBundleValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return NewBundleValueUnknown(), diags
	}

	return BundleValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewBundleValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BundleValue {
	object, diags := NewBundleValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBundleValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BundleType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBundleValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBundleValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBundleValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBundleValueMust(BundleValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BundleType) ValueType(ctx context.Context) attr.Value {
	return BundleValue{}
}

var _ basetypes.ObjectValuable = BundleValue{}

type BundleValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	state attr.ValueState
}

func (v BundleValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BundleValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BundleValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BundleValue) String() string {
	return "BundleValue"
}

func (v BundleValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id": v.Id,
		})

	return objVal, diags
}

func (v BundleValue) Equal(o attr.Value) bool {
	other, ok := o.(BundleValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v BundleValue) Type(ctx context.Context) attr.Type {
	return BundleType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BundleValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id": basetypes.StringType{},
	}
}
